OLD_APP_VERSION='v1.2.5-stable' # version précedente de l'application                                                                |  (default: 'v1.0.0-stable')
APP_VERSION='v1.2.6-stable' # version de l'application                                                                               |  (default: 'v1.1.0-stable')
APP_NAME='pyqt6-pdf-qrcode' # nom de l'application                                                                                   |  (default: 'pyqt6-pdf-qrcode')
NAVIGATION_MODE='KEYBOARD_MOUSE' # altérner entre 'JOYSTICK' et 'KEYBOARD_MOUSE'                                                     |  (default: 'KEYBOARD_MOUSE')
SCROLL_SPEED=0.75 # ajuster la vitesse de défilement (la valeur 0 est la plus rapide) (ne fonctionne qu'avec le mode joystick)       |  (default: 0.75)
SUPPORTED_DOCUMENT_EXTENSIONS=['html', 'pdf'] # extensions de documents supportées                                                   |  (default: ['html', 'pdf'])
SUPPORTED_VIDEO_EXTENSIONS=['mp4'] # extensions vidéo supportées                                                                     |  (default: ['mp4'])